# Site settings
title: Logic and Destructive Forces
header-img: img/home-bg.png
email: aasamuelj@gmail.com
copyright_name: AaronSamuelJ
description: > # this means to ignore newlines until "baseurl:"
  How Logic Improves the Computer and Human
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: The_Tweet_Head
github_username:  AaronSamuelJ
learn_profile: AaronSamuelJ
email_username: aasamuelj@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
